/**
 * Lucide icon barrel
 *
 * Import icons from this file so there is a single place to manage the set.
 * Spread LUCIDE_ICONS into a component's `imports: []` array to get all icons at once,
 * or import individual icons for components that only need a few.
 *
 * Usage:
 * ```typescript
 * import { LUCIDE_ICONS } from '../../../shared/lucide-icons';
 * @Component({ imports: [...LUCIDE_ICONS] })
 * ```
 * Template: <svg lucideChevronDown class="w-4 h-4"></svg>
 */

import {
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideUsers,
  LucideShieldCheck,
  LucideAward,
  LucideTag,
  LucideClipboardCheck,
  LucideDownload,
  LucideUser,
  LucideLogOut,
  LucideMenu,
  LucideX,
  LucidePlus,
  LucideTrash2,
  LucideMail,
  LucideMailOpen,
  LucideSmartphone,
  LucideRefreshCw,
  LucideTriangleAlert,
  LucideXCircle,
  LucideCircleCheck,
  LucideInfo,
  LucideDynamicIcon,
  LucideMessageSquare,
  LucideMessageCircle,
  LucideSend,
  LucidePin,
  LucidePinOff,
  LucideHash,
  LucideReply,
  LucideEdit2,
  LucideSettings,
  LucidePencil,
  LucideFileText,
  LucideSearch,
  LucideSmile,
  LucideCalendar,
  LucideMapPin,
} from '@lucide/angular';

export {
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideUsers,
  LucideShieldCheck,
  LucideAward,
  LucideTag,
  LucideClipboardCheck,
  LucideDownload,
  LucideUser,
  LucideLogOut,
  LucideMenu,
  LucideX,
  LucidePlus,
  LucideTrash2,
  LucideMail,
  LucideMailOpen,
  LucideSmartphone,
  LucideRefreshCw,
  LucideTriangleAlert,
  LucideXCircle,
  LucideCircleCheck,
  LucideInfo,
  LucideDynamicIcon,
  LucideMessageSquare,
  LucideMessageCircle,
  LucideSend,
  LucidePin,
  LucidePinOff,
  LucideHash,
  LucideReply,
  LucideEdit2,
  LucideSettings,
  LucidePencil,
  LucideFileText,
  LucideSearch,
  LucideSmile,
  LucideCalendar,
  LucideMapPin,
};

export const LUCIDE_ICONS = [
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideUsers,
  LucideShieldCheck,
  LucideAward,
  LucideTag,
  LucideClipboardCheck,
  LucideDownload,
  LucideUser,
  LucideLogOut,
  LucideMenu,
  LucideX,
  LucidePlus,
  LucideTrash2,
  LucideMail,
  LucideMailOpen,
  LucideSmartphone,
  LucideRefreshCw,
  LucideTriangleAlert,
  LucideXCircle,
  LucideCircleCheck,
  LucideInfo,
  LucideDynamicIcon,
  LucideMessageSquare,
  LucideMessageCircle,
  LucideSend,
  LucidePin,
  LucidePinOff,
  LucideHash,
  LucideReply,
  LucideEdit2,
  LucideSettings,
  LucidePencil,
  LucideFileText,
  LucideSearch,
  LucideSmile,
  LucideCalendar,
  LucideMapPin,
] as const;
